stacks:
  php:
    use: php
    with:
      php-version: 8.1
      extensions: apcu, bcmath, imagick, gd, intl, ldap, mysql, pgsql, redis
      tools:  composer:2
  node:
    use: node
    with:
      node-version: 16
      tools:  yarn:v1.22.19

apps:
  api:
    basepath: /api
    stack: php
    mounts:
      media: /media
      media-cache: /public/media
    build:
      - stack: php
        scripts:
          - composer install
          - composer dump-autoload --no-dev --classmap-authoritative
      - stack: node
        scripts:
          - yarn install
          - yarn build
    
  frontend:
    basepath: /app
    stack: node
    mounts:
      media: /media
      media-cache: /public/media
    build:
      - stack: node
        scripts:
          - yarn install
          - yarn build
