build :
  - image: registry.mezcalito.fr/julien.jacottet/k8s-stack-images/php:8.1-fpm
    scripts: |
      cd api
      composer install
      composer dump-autoload --no-dev --classmap-authoritative
  - image: node:16
    scripts: |
      cd frontend
      yarn install
      yarn build

mounts:
  media: /app/media
  media-cache: /app/public/media

#hooks:
#  postDeploy:
#    - image: registry.mezcalito.fr/julien.jacottet/k8s-stack-images/php:8.1-fpm
#      basepath: /api
#      scripts:
#        - ./bin/console d:m:m

apps:
  api:
    image: registry.mezcalito.fr/julien.jacottet/k8s-stack-images/php:8.1-fpm
    basepath: /api
    proxy:
      type: caddy
      caddyfile: .stack.io/Caddyfile
  frontend:
    image: node:16
    basepath: /app
    command: node server.js -p 9000

workers:
  queue:
    image: registry.mezcalito.fr/julien.jacottet/k8s-stack-images/php:8.1-fpm
    basepath: /api
    command: ./bin/console my:cmd

tasks:
  index:
    image: registry.mezcalito.fr/julien.jacottet/k8s-stack-images/php:8.1-fpm
    basepath: /api
    spec: '*/19 * * * *'
    command: ./bin/console app:index
