stacks:
  php:
    template: php:8.1
    recipes:
      composer: 2
      extensions: [ apcu, bcmath, imagick, gd, intl, ldap, mysql, pgsql, redis]
    scripts: |
      echo "A build command for php"

apps: 
  api: 
    basepath: /
    build:
      steps:
        exemple:
          stack: php
          script: |
            php -v

    runtime:
      stack: php
      hooks:
        post_deploy: ~

      web:
        locations:
            handle:
              "/":
                  root: ~
                  fpm: true
                  encode: [ zstd, gzip ]
                  file_server: true
         
