stacks:
  php:
    template: php:8.1
    recipes:
      composer: 2
      extensions: [ apcu, bcmath, imagick, gd, intl, ldap, mysql, pgsql, redis]
    script: |
      echo "A build command for php"

apps: 
  api: 
    basepath: /
    build:
      - stack: php
        script: |
          echo "step 1"
      - stack: php
        script: |
          echo "step 2"

    runtime:
      stack: php

#      web:
#        locations:
#            handle:
#              "/":
#                  root: ~
#                  fpm: true
#                  encode: [ zstd, gzip ]
#                  file_server: true
         
