stacks:
  php:
    template: php:8.1
    recipes:
      composer: 2
      extensions: [ apcu, bcmath, imagick, gd, intl, ldap, mysql, pgsql, redis]
    script: |
      echo "A build command for php"
  node:
    template: node:16
    recipes:
      composer: 2
      extensions: [ apcu, bcmath, imagick, gd, intl, ldap, mysql, pgsql, redis]
    script: |
      echo "A build command for php"


apps: 
  api: 
    basepath: /api
    build:
      - stack: php
        script: |
          composer install
          composer dump-autoload --no-dev --classmap-authoritative

    runtime:
      stack: php

  frontend: 
    basepath: /frontend
    build:
      - stack: node
        script: |
          echo "install node"

    runtime:
      stack: node

