build :
  - image: php:8.1
    basepath: /api
    scripts:
      - composer install
      - composer dump-autoload --no-dev --classmap-authoritative
  - image: node:16
    basepath: /api
    scripts:
      - yarn install
      - yarn build

mounts:
  media: /app/media
  media-cache: /app/public/media

#hooks:
#  postDeploy:
#    - image: php:8.1
#      basepath: /api
#      scripts:
#        - ./bin/console d:m:m

apps:
  api:
    image: php:8.1
    basepath: /api
    proxy:
      type: caddy
      caddyfile: .stack.io/Caddyfile
  frontend:
    image: node:16
    basepath: /app
    command: node server.js -p 9000

workers:
  queue:
    image: php:8.1
    basepath: /api
    command: ./bin/console my:cmd

tasks:
  index:
    image: php:8.1
    basepath: /api
    spec: '*/19 * * * *'
    command: ./bin/console app:index
